import { SEED_AGENCIES as A } from "@/lib/agencies/seed"
import type { Property } from "@/lib/properties/types"

/**
 * Datos de prueba (no son avisos reales). Cubren los diez tipos, las tres operaciones y la
 * mayoría de las zonas, con casos borde a propósito: "Consultar precio", una venta en pesos,
 * direcciones ocultas, propiedades sin foto, una a estrenar. Las coordenadas son aproximadas
 * por zona. Las fotos se reparten por parecido; las reales llegan con el hito 2.
 */
const F = (...nombres: string[]) => nombres.map((n) => `/images/properties/${n}.webp`)

export const SEED_PROPERTIES: Property[] = [
  // ── Venta ────────────────────────────────────────────────────────────────
  {
    id: "bol-01", operation: "venta", type: "casa", zone: "centro",
    title: "Casa de dos plantas sobre Av. San Martín",
    description: "Casa contemporánea en dos plantas sobre la avenida principal. Living en doble altura con hogar a leña, cocina integrada con isla y ventanales al jardín.\n\nArriba, suite con vestidor y dos dormitorios con placard. En el fondo, quincho con parrilla y pileta.",
    price: 185_000, currency: "USD", address: "Av. San Martín 845", showAddress: true,
    lat: -36.2295, lng: -61.1138, areaTotalM2: 300, areaCoveredM2: 210, rooms: 5, beds: 3, baths: 2, garages: 2, ageYears: 6,
    features: ["cochera", "pileta", "patio", "parrilla", "apto-credito"],
    photos: F("house-1", "house-5", "apt-1"), publishedAt: "2026-10-05", featured: true, agency: A.norte,
  },
  {
    id: "bol-02", operation: "venta", type: "casa", zone: "casariego",
    title: "Casa de 3 dormitorios con patio",
    description: "Casa en una planta, a dos cuadras del club. Tres dormitorios, living comedor, cocina con salida al patio y garaje.",
    price: 98_000, currency: "USD", address: "Casariego 1240", showAddress: true,
    lat: -36.2221, lng: -61.1252, areaTotalM2: 250, areaCoveredM2: 140, rooms: 4, beds: 3, baths: 1, garages: 1, ageYears: 25,
    features: ["cochera", "patio", "apto-credito"],
    photos: F("house-5", "house-1"), publishedAt: "2026-09-28", agency: A.centro,
  },
  {
    id: "bol-03", operation: "venta", type: "casa", zone: "villa-melitona",
    title: "Casa familiar con quincho",
    description: "Casa de tres dormitorios con quincho, parrilla y fondo parquizado. Lista para mudarse.",
    price: 120_000, currency: "USD", address: "Las Palmeras 655", showAddress: true,
    lat: -36.2189, lng: -61.1121, areaTotalM2: 400, areaCoveredM2: 160, rooms: 4, beds: 3, baths: 2, garages: 1, ageYears: 15,
    features: ["cochera", "patio", "parrilla"],
    photos: F("house-1"), publishedAt: "2026-09-20", agency: A.norte,
  },
  {
    id: "bol-04", operation: "venta", type: "casa", zone: "las-flores",
    title: "Casa de 2 dormitorios para entrar a vivir",
    description: "Casa chica y cuidada, ideal primera vivienda. Dos dormitorios, cocina comedor y patio con parrilla.",
    price: 68_000, currency: "USD", address: "Los Jazmines 230", showAddress: true,
    lat: -36.2287, lng: -61.1003, areaTotalM2: 200, areaCoveredM2: 85, rooms: 3, beds: 2, baths: 1, ageYears: 30,
    features: ["patio", "parrilla", "apto-credito"],
    photos: F("house-5"), publishedAt: "2026-09-12", agency: A.campoCiudad,
  },
  {
    id: "bol-05", operation: "venta", type: "casa", zone: "san-jose",
    title: "Casa amplia en lote de esquina",
    description: "Casa de cuatro dormitorios en lote de esquina, con cochera doble y pileta.",
    price: 145_000, currency: "USD", address: "Sarmiento 980", showAddress: true,
    lat: -36.2312, lng: -61.1279, areaTotalM2: 520, areaCoveredM2: 230, rooms: 6, beds: 4, baths: 2, garages: 2, ageYears: 18,
    features: ["cochera", "pileta", "patio", "parrilla"],
    photos: F("house-1", "house-3"), publishedAt: "2026-08-30", agency: A.bolivarHomes,
  },
  {
    id: "bol-06", operation: "venta", type: "casa", zone: "centro",
    title: "Casona de estilo a reciclar",
    description: "Casa de principios de siglo, techos altos y patio con aljibe. Para reciclar a gusto, a una cuadra de la plaza.",
    price: 110_000, currency: "USD", address: "Belgrano 512", showAddress: true,
    lat: -36.2318, lng: -61.1159, areaTotalM2: 380, areaCoveredM2: 260, rooms: 6, beds: 4, baths: 2, ageYears: 90,
    features: ["patio"],
    photos: F("house-4", "house-2"), publishedAt: "2026-08-14", agency: A.centro,
  },
  {
    id: "bol-07", operation: "venta", type: "ph", zone: "centro",
    title: "PH reciclado con patio",
    description: "PH al frente, sin expensas, con patio y terraza propia. Dos dormitorios y cocina nueva.",
    price: 95_000, currency: "USD", address: "Rivadavia 1120", showAddress: true,
    lat: -36.2331, lng: -61.1127, areaTotalM2: 110, areaCoveredM2: 85, rooms: 3, beds: 2, baths: 1, ageYears: 40,
    features: ["patio", "parrilla", "apto-credito"],
    photos: F("house-2", "apt-2"), publishedAt: "2026-10-02", featured: true, agency: A.norte,
  },
  {
    id: "bol-08", operation: "venta", type: "departamento", zone: "centro",
    title: "Departamento de 2 dormitorios con balcón",
    description: "A metros de la plaza. Living comedor con balcón, cocina separada y dos dormitorios.",
    price: 78_000, currency: "USD", expenses: 45_000, address: "Alvear 233, 3° B", showAddress: true,
    lat: -36.2302, lng: -61.1149, areaCoveredM2: 72, rooms: 3, beds: 2, baths: 1, ageYears: 12,
    features: ["apto-credito"],
    photos: F("apt-1", "apt-3"), publishedAt: "2026-09-25", agency: A.centro,
  },
  {
    id: "bol-09", operation: "venta", type: "departamento", zone: "centro",
    title: "Monoambiente a estrenar",
    description: "Monoambiente en edificio nuevo, con cocina integrada y balcón. Ideal inversión.",
    price: 48_000, currency: "USD", expenses: 30_000, address: "Mitre 410, 2° A", showAddress: true,
    lat: -36.2296, lng: -61.1162, areaCoveredM2: 34, rooms: 1, beds: 0, baths: 1, ageYears: 0,
    features: ["a-estrenar", "apto-credito"],
    photos: F("apt-2", "apt-3"), publishedAt: "2026-10-06", agency: A.bolivarHomes,
  },
  {
    id: "bol-10", operation: "venta", type: "departamento", zone: "san-juan",
    title: "Departamento de 3 ambientes con cochera",
    description: "Tres ambientes en planta baja, con patio chico y cochera cubierta.",
    price: 72_000, currency: "USD", expenses: 25_000, address: "Moreno 785", showAddress: true,
    lat: -36.2361, lng: -61.1182, areaCoveredM2: 68, rooms: 3, beds: 2, baths: 1, garages: 1, ageYears: 8,
    features: ["cochera", "patio"],
    photos: F("apt-3", "apt-1"), publishedAt: "2026-09-08", agency: A.norte,
  },
  {
    id: "bol-11", operation: "venta", type: "departamento", zone: "centro",
    title: "Departamento amplio de 3 dormitorios",
    description: "Piso alto con vista a la plaza. Tres dormitorios, dos baños y lavadero.",
    price: 115_000, currency: "USD", expenses: 60_000, address: "Avenida Alsina 205, 6°", showAddress: true,
    lat: -36.2309, lng: -61.1131, areaCoveredM2: 110, rooms: 4, beds: 3, baths: 2, ageYears: 20,
    features: [],
    photos: F("apt-1"), publishedAt: "2026-07-30", agency: A.centro,
  },
  {
    id: "bol-12", operation: "venta", type: "terreno", zone: "casariego",
    title: "Lote residencial de 10 × 30",
    description: "Lote con todos los servicios en barrio consolidado. Escritura inmediata.",
    price: 28_000, currency: "USD", address: "Calle 14 entre 9 y 11", showAddress: true,
    lat: -36.2209, lng: -61.1268, areaTotalM2: 300,
    features: [],
    photos: F("lot-1"), publishedAt: "2026-09-18", agency: A.campoCiudad,
  },
  {
    id: "bol-13", operation: "venta", type: "terreno", zone: "las-flores",
    title: "Lote sobre avenida, apto comercio",
    description: "Lote de esquina sobre avenida, ideal local o galpón chico.",
    price: 42_000, currency: "USD", address: "Avenida General Paz y Los Ceibos", showAddress: true,
    lat: -36.2276, lng: -61.0985, areaTotalM2: 450,
    features: [],
    photos: F("lot-2"), publishedAt: "2026-08-22", agency: A.bolivarHomes,
  },
  {
    id: "bol-14", operation: "venta", type: "terreno", zone: "villa-diamante",
    title: "Lote en pesos, financiado",
    description: "Lote de 10 × 25 con agua y luz. Se vende en pesos, con anticipo y cuotas.",
    price: 18_500_000, currency: "ARS", address: "Los Sauces 150", showAddress: true,
    lat: -36.2402, lng: -61.0981, areaTotalM2: 250,
    features: [],
    photos: F("lot-1"), publishedAt: "2026-09-02", agency: A.campoCiudad,
  },
  {
    id: "bol-15", operation: "venta", type: "terreno", zone: "quintas",
    title: "Lote de 1.000 m² en zona de quintas",
    description: "Lote parquizado con frente sobre camino mejorado, a 5 minutos del centro.",
    price: 35_000, currency: "USD", address: "Camino a las quintas, lote 12", showAddress: true,
    lat: -36.2058, lng: -61.1405, areaTotalM2: 1000,
    features: [],
    photos: F("lot-1", "house-3"), publishedAt: "2026-07-15", agency: A.norte,
  },
  {
    id: "bol-16", operation: "venta", type: "quinta", zone: "quintas",
    title: "Casa quinta con pileta y parque",
    description: "Quinta de 2.500 m² con casa de tres dormitorios, pileta, quincho y parque arbolado.",
    price: 160_000, currency: "USD", address: "Camino a las quintas, lote 4", showAddress: false,
    lat: -36.2071, lng: -61.1382, areaTotalM2: 2500, areaCoveredM2: 180, rooms: 5, beds: 3, baths: 2, garages: 2, ageYears: 20,
    features: ["pileta", "parrilla", "patio", "cochera"],
    photos: F("house-3", "house-5", "apt-1"), publishedAt: "2026-10-01", featured: true, agency: A.campoCiudad,
  },
  {
    id: "bol-17", operation: "venta", type: "quinta", zone: "quintas",
    title: "Quinta chica para fin de semana",
    description: "Casa de dos dormitorios en 1.200 m², con pileta y parrilla.",
    price: 92_000, currency: "USD", address: "Ruta 226, km 312", showAddress: true,
    lat: -36.2556, lng: -61.0851, areaTotalM2: 1200, areaCoveredM2: 90, rooms: 3, beds: 2, baths: 1, ageYears: 12,
    features: ["pileta", "parrilla", "patio"],
    photos: F("house-3"), publishedAt: "2026-08-05", agency: A.bolivarHomes,
  },
  {
    id: "bol-18", operation: "venta", type: "quinta", zone: "urdampilleta",
    title: "Casa quinta en Urdampilleta",
    description: "Quinta tranquila en las afueras de Urdampilleta, con monte de árboles y galpón.",
    price: 70_000, currency: "USD", address: "Urdampilleta, acceso norte", showAddress: true,
    lat: -36.4294, lng: -61.4192, areaTotalM2: 3000, areaCoveredM2: 120, rooms: 4, beds: 2, baths: 1, ageYears: 35,
    features: ["patio", "parrilla"],
    photos: F("house-3", "lot-1"), publishedAt: "2026-06-20", agency: A.campoCiudad,
  },
  {
    id: "bol-19", operation: "venta", type: "campo", zone: "rural",
    title: "Campo agrícola de 120 ha",
    description: "Campo mixto con buena aptitud agrícola, molino, aguadas y casa de casero. Acceso por camino vecinal.",
    price: null, currency: "USD", address: "Cuartel II, camino vecinal", showAddress: false,
    lat: -36.3012, lng: -61.2054, areaHa: 120,
    features: [],
    photos: F("lot-1"), publishedAt: "2026-09-10", agency: A.campoCiudad,
  },
  {
    id: "bol-20", operation: "venta", type: "campo", zone: "pirovano",
    title: "Campo ganadero cerca de Pirovano",
    description: "Campo de 350 ha con alambrados, manga y casa principal.",
    price: 1_400_000, currency: "USD", address: "Pirovano, ruta 65", showAddress: true,
    lat: -36.5098, lng: -61.5571, areaHa: 350,
    features: [],
    photos: F("lot-1"), publishedAt: "2026-07-01", agency: A.campoCiudad,
  },
  {
    id: "bol-21", operation: "venta", type: "local", zone: "centro",
    title: "Local comercial en esquina céntrica",
    description: "Local de 80 m² con vidriera a dos calles, baño y depósito.",
    price: null, currency: "USD", address: "Avenida San Martín y Belgrano", showAddress: true,
    lat: -36.2314, lng: -61.1141, areaCoveredM2: 80, baths: 1,
    features: [],
    photos: F("house-4"), publishedAt: "2026-08-25", agency: A.norte,
  },
  {
    id: "bol-22", operation: "venta", type: "galpon", zone: "la-ganadera",
    title: "Galpón de 400 m² con oficina",
    description: "Galpón con portón alto, oficina y baño. Acceso para camiones.",
    price: 135_000, currency: "USD", address: "Avenida Almirante Brown 2100", showAddress: true,
    lat: -36.2431, lng: -61.1253, areaTotalM2: 800, areaCoveredM2: 400, baths: 1,
    features: [],
    photos: [], publishedAt: "2026-06-12", agency: A.bolivarHomes,
  },

  // ── Alquiler ─────────────────────────────────────────────────────────────
  {
    id: "bol-23", operation: "alquiler", type: "departamento", zone: "centro",
    title: "Departamento luminoso a una cuadra de la plaza",
    description: "Semipiso con balcón terraza. Living comedor, cocina independiente y dos dormitorios.",
    price: 380_000, currency: "ARS", expenses: 55_000, address: "Belgrano 320, 4°", showAddress: true,
    lat: -36.2312, lng: -61.1151, areaCoveredM2: 68, rooms: 3, beds: 2, baths: 1, ageYears: 10,
    features: [],
    photos: F("apt-1", "apt-2"), publishedAt: "2026-10-04", featured: true, agency: A.centro,
  },
  {
    id: "bol-24", operation: "alquiler", type: "departamento", zone: "centro",
    title: "Monoambiente amoblado",
    description: "Monoambiente equipado, ideal estudiante o profesional. Incluye wifi.",
    price: 260_000, currency: "ARS", expenses: 30_000, address: "Pinto 512, 1° C", showAddress: true,
    lat: -36.2289, lng: -61.1172, areaCoveredM2: 32, rooms: 1, beds: 0, baths: 1, ageYears: 5,
    features: ["amoblado"],
    photos: F("apt-2"), publishedAt: "2026-09-30", agency: A.bolivarHomes,
  },
  {
    id: "bol-25", operation: "alquiler", type: "departamento", zone: "san-juan",
    title: "Departamento de 2 dormitorios con patio",
    description: "Planta baja con patio propio. Acepta mascotas chicas.",
    price: 350_000, currency: "ARS", address: "Moreno 790", showAddress: true,
    lat: -36.2365, lng: -61.1186, areaCoveredM2: 60, rooms: 3, beds: 2, baths: 1, ageYears: 8,
    features: ["patio", "mascotas"],
    photos: F("apt-3", "apt-1"), publishedAt: "2026-09-15", agency: A.norte,
  },
  {
    id: "bol-26", operation: "alquiler", type: "departamento", zone: "colombo",
    title: "Departamento de 1 dormitorio",
    description: "Un dormitorio, cocina integrada y lavadero. Bajas expensas.",
    price: 290_000, currency: "ARS", expenses: 15_000, address: "Colón 1530, PB", showAddress: true,
    lat: -36.2408, lng: -61.1097, areaCoveredM2: 42, rooms: 2, beds: 1, baths: 1, ageYears: 14,
    features: [],
    photos: F("apt-2", "apt-3"), publishedAt: "2026-08-28", agency: A.centro,
  },
  {
    id: "bol-27", operation: "alquiler", type: "casa", zone: "villa-melitona",
    title: "Casa de 3 dormitorios con cochera",
    description: "Casa con patio y parrilla, cochera cubierta. Acepta mascotas.",
    price: 520_000, currency: "ARS", address: "Las Rosas 420", showAddress: true,
    lat: -36.2196, lng: -61.1108, areaTotalM2: 300, areaCoveredM2: 130, rooms: 4, beds: 3, baths: 1, garages: 1, ageYears: 22,
    features: ["cochera", "patio", "parrilla", "mascotas"],
    photos: F("house-5", "house-1"), publishedAt: "2026-10-03", agency: A.norte,
  },
  {
    id: "bol-28", operation: "alquiler", type: "casa", zone: "los-tilos",
    title: "Casa de 2 dormitorios",
    description: "Casa sencilla con patio, cerca de escuelas.",
    price: 420_000, currency: "ARS", address: "Los Claveles 85", showAddress: true,
    lat: -36.2203, lng: -61.1002, areaTotalM2: 220, areaCoveredM2: 90, rooms: 3, beds: 2, baths: 1, ageYears: 30,
    features: ["patio"],
    photos: F("house-5"), publishedAt: "2026-09-05", agency: A.campoCiudad,
  },
  {
    id: "bol-29", operation: "alquiler", type: "casa", zone: "centro",
    title: "Casa céntrica amoblada",
    description: "Casa de tres dormitorios amoblada, a dos cuadras de la plaza.",
    price: 650_000, currency: "ARS", address: "Alvear 610", showAddress: true,
    lat: -36.2328, lng: -61.1153, areaTotalM2: 280, areaCoveredM2: 170, rooms: 5, beds: 3, baths: 2, ageYears: 35,
    features: ["amoblado", "patio", "parrilla"],
    photos: F("house-4", "apt-1"), publishedAt: "2026-07-20", agency: A.centro,
  },
  {
    id: "bol-30", operation: "alquiler", type: "local", zone: "centro",
    title: "Local sobre Av. San Martín",
    description: "Local de 60 m² con vidriera sobre la avenida comercial.",
    price: 700_000, currency: "ARS", address: "Avenida San Martín 620", showAddress: true,
    lat: -36.2301, lng: -61.1136, areaCoveredM2: 60, baths: 1,
    features: [],
    photos: F("house-4"), publishedAt: "2026-09-22", agency: A.bolivarHomes,
  },
  {
    id: "bol-31", operation: "alquiler", type: "local", zone: "las-flores",
    title: "Local de barrio con depósito",
    description: "Local de 45 m² con depósito y baño, en zona de mucho paso.",
    price: 380_000, currency: "ARS", address: "Avenida General Paz 340", showAddress: true,
    lat: -36.2268, lng: -61.1018, areaCoveredM2: 45, baths: 1,
    features: [],
    photos: F("lot-2"), publishedAt: "2026-08-10", agency: A.campoCiudad,
  },
  {
    id: "bol-32", operation: "alquiler", type: "oficina", zone: "centro",
    title: "Oficina en primer piso",
    description: "Oficina de dos ambientes con recepción, ideal estudio profesional.",
    price: 330_000, currency: "ARS", expenses: 20_000, address: "Avenida Alsina 180, 1°", showAddress: true,
    lat: -36.2306, lng: -61.1124, areaCoveredM2: 40, rooms: 2, baths: 1, ageYears: 25,
    features: [],
    photos: F("apt-3"), publishedAt: "2026-09-27", agency: A.centro,
  },
  {
    id: "bol-33", operation: "alquiler", type: "cochera", zone: "centro",
    title: "Cochera cubierta en el centro",
    description: "Cochera fija cubierta, con portón automático.",
    price: 60_000, currency: "ARS", address: "Mitre 455", showAddress: true,
    lat: -36.2299, lng: -61.1168, areaCoveredM2: 14,
    features: [],
    photos: [], publishedAt: "2026-10-06", agency: A.norte,
  },

  // ── Temporario ───────────────────────────────────────────────────────────
  {
    id: "bol-34", operation: "temporario", type: "quinta", zone: "quintas",
    title: "Quinta con pileta para fines de semana",
    description: "Quinta para 8 personas con pileta, quincho y parque. Se alquila por día o fin de semana.",
    price: 180_000, currency: "ARS", address: "Camino a las quintas, lote 9", showAddress: false,
    lat: -36.2045, lng: -61.1421, areaTotalM2: 3000, areaCoveredM2: 150, rooms: 4, beds: 3, baths: 2, ageYears: 15,
    features: ["pileta", "parrilla", "patio", "mascotas"],
    photos: F("house-3", "house-1"), publishedAt: "2026-10-07", featured: true, agency: A.campoCiudad,
  },
  {
    id: "bol-35", operation: "temporario", type: "quinta", zone: "quintas",
    title: "Quinta familiar con quincho",
    description: "Ideal cumpleaños y reuniones. Quincho cerrado, parrilla y juegos.",
    price: 140_000, currency: "ARS", address: "Ruta 226, km 314", showAddress: true,
    lat: -36.2571, lng: -61.0838, areaTotalM2: 2000, areaCoveredM2: 110, rooms: 3, beds: 2, baths: 1, ageYears: 20,
    features: ["pileta", "parrilla", "patio"],
    photos: F("house-3"), publishedAt: "2026-09-19", agency: A.bolivarHomes,
  },
  {
    id: "bol-36", operation: "temporario", type: "casa", zone: "centro",
    title: "Casa céntrica por día",
    description: "Casa equipada para 4 personas, a pasos de la plaza. Ideal visitas y eventos.",
    price: 70_000, currency: "ARS", address: "Rivadavia 845", showAddress: true,
    lat: -36.2322, lng: -61.1118, areaCoveredM2: 90, rooms: 3, beds: 2, baths: 1, ageYears: 40,
    features: ["amoblado", "patio"],
    photos: F("house-2", "apt-2"), publishedAt: "2026-08-18", agency: A.centro,
  },
]
