import { SEED_AGENCIES } from "@/lib/agencies/seed"
import type { Property } from "@/lib/properties/types"

/** Inventario real y representativo de San Carlos de Bolívar para filtros, mapa y contacto. */
export const SEED_PROPERTIES: Property[] = [
  {
    id: "bol-01",
    title: "Casa de dos plantas sobre Av. San Martín",
    type: "house",
    price: 185000,
    currency: "USD",
    operation: "sale",
    beds: 3,
    baths: 2,
    areaM2: 210,
    address: "Av. San Martín 845, Bolívar",
    neighborhood: "Centro Residencial",
    lat: -36.2295,
    lng: -61.1138,
    photoCount: 12,
    coverUrl: "/images/properties/house-1.jpg",
    photos: [
      "/images/properties/house-1.jpg",
      "/images/hero/hero.jpg",
    ],
    featured: true,
    description:
      "Imponente residencia contemporánea desarrollada en dos plantas en la arteria principal de Bolívar. Cuenta con amplio living en doble altura con hogar a leña, cocina integrada con isla de mármol y ventanales panorámicos al jardín parquizado. En planta alta, máster suite con vestidor y dos dormitorios adicionales con placard completo. Fondo con quincho cubierto, parrilla de acero y piscina climatizada.",
    features: [
      "Calefacción por losa radiante",
      "Piscina climatizada con solárium",
      "Quincho cubierto con asador",
      "Cochera cubierta para 2 vehículos",
      "Aberturas DVH de alta prestación",
      "Gas natural y todos los servicios",
    ],
    agency: {
      name: SEED_AGENCIES.norte.name,
      logoUrl: SEED_AGENCIES.norte.logoUrl,
      phone: SEED_AGENCIES.norte.phone,
      email: SEED_AGENCIES.norte.email,
      address: SEED_AGENCIES.norte.address,
    },
  },
  {
    id: "bol-02",
    title: "Depto luminoso a una cuadra de la plaza",
    type: "apartment",
    price: 280000,
    currency: "ARS",
    operation: "rent",
    beds: 2,
    baths: 1,
    areaM2: 68,
    address: "Belgrano 320, Bolívar",
    neighborhood: "Plaza 1810 / Centro",
    lat: -36.2312,
    lng: -61.1151,
    photoCount: 8,
    coverUrl: "/images/properties/apt-1.jpg",
    photos: [
      "/images/properties/apt-1.jpg",
    ],
    featured: true,
    description:
      "Semipiso de categoría a metros de la Plaza 1810 y el centro comercial. Living comedor con salida a balcón terraza aterrazado con vista abierta a la copa de los árboles. Cocina independiente con muebles bajo mesada y alacenas a medida. Dos dormitorios con pisos de madera flotante y placard embutido. Baño completo con bañera y ventilación natural. Bajas expensas.",
    features: [
      "Balcón terraza con vista a la plaza",
      "Pisos de madera flotante",
      "Cocina independiente equipada",
      "Excelente ventilación cruzada",
      "Conexión para lavarropas",
      "Edificio con ascensor de última generación",
    ],
    agency: {
      name: SEED_AGENCIES.centro.name,
      logoUrl: SEED_AGENCIES.centro.logoUrl,
      phone: SEED_AGENCIES.centro.phone,
      email: SEED_AGENCIES.centro.email,
      address: SEED_AGENCIES.centro.address,
    },
  },
  {
    id: "bol-03",
    title: "Lote residencial barrio Las Acacias",
    type: "lot",
    price: 42000,
    currency: "USD",
    operation: "sale",
    beds: 0,
    baths: 0,
    areaM2: 600,
    address: "Calle 14 entre 9 y 11, Bolívar",
    neighborhood: "Barrio Las Acacias",
    lat: -36.2268,
    lng: -61.1089,
    photoCount: 4,
    coverUrl: "/images/properties/lot-1.jpg",
    photos: [
      "/images/properties/lot-1.jpg",
    ],
    description:
      "Excelente lote residencial de 20 metros de frente por 30 metros de fondo en el consolidado barrio Las Acacias. Entorno sereno con construcciones modernas, arboleda añosa y calle consolidada con cordón cuneta. Escrituración inmediata, amojonado y con servicios en puerta: tendido eléctrico, agua corriente y gas en la vereda.",
    features: [
      "Medidas: 20 m de frente x 30 m de fondo",
      "Escrituración y planos listos",
      "Tendido eléctrico subterráneo",
      "Agua corriente y gas en vereda",
      "Barrio en constante valorización",
    ],
    agency: {
      name: SEED_AGENCIES.campoCiudad.name,
      logoUrl: SEED_AGENCIES.campoCiudad.logoUrl,
      phone: SEED_AGENCIES.campoCiudad.phone,
      email: SEED_AGENCIES.campoCiudad.email,
      address: SEED_AGENCIES.campoCiudad.address,
    },
  },
  {
    id: "bol-04",
    title: "PH reciclado con patio",
    type: "house",
    price: 95000,
    currency: "USD",
    operation: "sale",
    beds: 2,
    baths: 1,
    areaM2: 95,
    address: "Rivadavia 1120, Bolívar",
    neighborhood: "Barrio Pompeya",
    lat: -36.2331,
    lng: -61.1172,
    photoCount: 15,
    coverUrl: "/images/properties/house-2.jpg",
    photos: [
      "/images/properties/house-2.jpg",
    ],
    description:
      "Propiedad de autor totalmente restaurada conservando su esencia original con toques de diseño industrial. Fachada de ladrillo a la vista restaurado, aberturas de hierro negro con vidrio repartido y techos altos. Cómodo patio privado interno con pisos damero, pérgola con guirnaldas de luces y canteros con vegetación autóctona. Sin expensas.",
    features: [
      "Sin expensas / Entrada independiente",
      "Patio privado con pérgola e iluminación",
      "Ladrillo a la vista tratado y techos altos",
      "Instalaciones eléctricas y sanitarias 100% nuevas",
      "Cocina tipo americana con isla desayunadora",
    ],
    agency: {
      name: SEED_AGENCIES.norte.name,
      logoUrl: SEED_AGENCIES.norte.logoUrl,
      phone: SEED_AGENCIES.norte.phone,
      email: SEED_AGENCIES.norte.email,
      address: SEED_AGENCIES.norte.address,
    },
  },
  {
    id: "bol-05",
    title: "Monoambiente amoblado centro",
    type: "apartment",
    price: 195000,
    currency: "ARS",
    operation: "rent",
    beds: 1,
    baths: 1,
    areaM2: 38,
    address: "Pinto 512, Bolívar",
    neighborhood: "Centro",
    lat: -36.2301,
    lng: -61.1148,
    photoCount: 6,
    coverUrl: "/images/properties/apt-2.jpg",
    photos: [
      "/images/properties/apt-2.jpg",
    ],
    description:
      "Departamento monoambiente de concepto abierto con mobiliario integral a medida en pleno centro de Bolívar. Cuenta con barra desayunadora de mármol, anafe vitrocerámico, sommier de 2 plazas, amplio ventanal con vista panorámica a la ciudad y luminarias colgantes de diseño. Ideal profesionales, estudiantes o estadías corporativas.",
    features: [
      "Totalmente amoblado y decorado",
      "Barra desayunadora con banquetas de diseño",
      "Aire acondicionado split frío/calor",
      "Conexión Wi-Fi de alta velocidad lista",
      "Edificio con control de acceso electrónico",
    ],
    agency: {
      name: SEED_AGENCIES.bolivarHomes.name,
      logoUrl: SEED_AGENCIES.bolivarHomes.logoUrl,
      phone: SEED_AGENCIES.bolivarHomes.phone,
      email: SEED_AGENCIES.bolivarHomes.email,
      address: SEED_AGENCIES.bolivarHomes.address,
    },
  },
  {
    id: "bol-06",
    title: "Casa quinta a 5 min del centro",
    type: "house",
    price: 145000,
    currency: "USD",
    operation: "sale",
    beds: 4,
    baths: 2,
    areaM2: 280,
    address: "Ruta 226 Km 312, Bolívar",
    neighborhood: "Suburbano Ruta 226",
    lat: -36.2385,
    lng: -61.102,
    photoCount: 18,
    coverUrl: "/images/properties/house-3.jpg",
    photos: [
      "/images/properties/house-3.jpg",
    ],
    featured: true,
    description:
      "Excepcional quinta de descanso ubicada sobre el acceso por Ruta 226, a solo 5 minutos del centro de Bolívar. Sobre un parque arbolado de 2.500 m² con añosa plantación de eucaliptos y sauces. Casa principal con gran galería cubierta, 4 amplios dormitorios, salón con hogar a leña y cocina de campo. Piscina con solárium atérmico y quincho con horno a leña.",
    features: [
      "Parque arbolado de 2.500 m²",
      "Piscina con borde atérmico y luces subacuáticas",
      "Gran galería perimetral tradicional",
      "Quincho con parrilla y horno de barro",
      "Fácil acceso pavimentado sobre Ruta 226",
      "Portón automatizado perimetral",
    ],
    agency: {
      name: SEED_AGENCIES.campoCiudad.name,
      logoUrl: SEED_AGENCIES.campoCiudad.logoUrl,
      phone: SEED_AGENCIES.campoCiudad.phone,
      email: SEED_AGENCIES.campoCiudad.email,
      address: SEED_AGENCIES.campoCiudad.address,
    },
  },
  {
    id: "bol-07",
    title: "Depto 3 ambientes con cochera",
    type: "apartment",
    price: 78000,
    currency: "USD",
    operation: "sale",
    beds: 3,
    baths: 2,
    areaM2: 92,
    address: "Alsina 780, Bolívar",
    neighborhood: "Barrio Parque",
    lat: -36.2284,
    lng: -61.1165,
    photoCount: 10,
    coverUrl: "/images/properties/apt-3.jpg",
    photos: [
      "/images/properties/apt-3.jpg",
    ],
    description:
      "Departamento de 3 ambientes a estrenar en moderno edificio boutique sobre calle Alsina. Orientación este con sol de mañana en todos los ambientes. Amplio estar comedor con balcón aterrazado vidriado, cocina semiseparada con mesadas de silestone, suite principal con antebaño y dos dormitorios secundarios. Incluye cochera cubierta con portón automatizado.",
    features: [
      "Cochera fija cubierta con portón levadizo",
      "Caldera dual individual y losa radiante",
      "Balcón con barandas de vidrio templado",
      "Griferías de alta gama y sanitarios suspendidos",
      "Portero visor con cámara de seguridad",
    ],
    agency: {
      name: SEED_AGENCIES.centro.name,
      logoUrl: SEED_AGENCIES.centro.logoUrl,
      phone: SEED_AGENCIES.centro.phone,
      email: SEED_AGENCIES.centro.email,
      address: SEED_AGENCIES.centro.address,
    },
  },
  {
    id: "bol-08",
    title: "Local + vivienda en esquina comercial",
    type: "house",
    price: 450000,
    currency: "ARS",
    operation: "rent",
    beds: 2,
    baths: 1,
    areaM2: 140,
    address: "Av. Bolívar y Sarmiento",
    neighborhood: "Esquina Comercial",
    lat: -36.2318,
    lng: -61.1122,
    photoCount: 9,
    coverUrl: "/images/properties/house-4.jpg",
    photos: [
      "/images/properties/house-4.jpg",
    ],
    description:
      "Punto neurálgico inmejorable en la intersección de Av. Bolívar y Sarmiento. En planta baja, local comercial con amplia ochava y vidrieras blindex de doble altura con máxima visibilidad peatonal y vehicular. En planta alta, vivienda independiente o sector de oficinas privadas con dos dormitorios, estar y cocina completa. Ideal para showroom o empresa.",
    features: [
      "Vidrieras panorámicas de doble altura sobre ochava",
      "Doble acceso independiente (local y vivienda)",
      "Alto caudal de tránsito peatonal y vehicular",
      "Persiana metálica motorizada",
      "Servicios trifásicos instalados",
    ],
    agency: {
      name: SEED_AGENCIES.bolivarHomes.name,
      logoUrl: SEED_AGENCIES.bolivarHomes.logoUrl,
      phone: SEED_AGENCIES.bolivarHomes.phone,
      email: SEED_AGENCIES.bolivarHomes.email,
      address: SEED_AGENCIES.bolivarHomes.address,
    },
  },
  {
    id: "bol-09",
    title: "Lote comercial sobre avenida",
    type: "lot",
    price: 68000,
    currency: "USD",
    operation: "sale",
    beds: 0,
    baths: 0,
    areaM2: 450,
    address: "Av. San Martín 1500, Bolívar",
    neighborhood: "Avenida Comercial",
    lat: -36.2249,
    lng: -61.111,
    photoCount: 3,
    coverUrl: "/images/properties/lot-2.jpg",
    photos: [
      "/images/properties/lot-2.jpg",
    ],
    description:
      "Fracción comercial de 450 m² (15 m de frente por 30 m de fondo) con ubicación estratégica sobre la traza ensanchada de Av. San Martín. Zonificación habilitada para depósito, concesionaria, supermercado o desarrollo de locales y departamentos en altura. Nivelado, cercado y con servicios disponibles.",
    features: [
      "15 metros lineales de frente sobre avenida principal",
      "Zonificación C1 (Comercial y Residencial mixta)",
      "Factibilidad de construcción en altura FOT y FOS amplios",
      "Asfalto reforzado y alumbrado público LED",
    ],
    agency: {
      name: SEED_AGENCIES.norte.name,
      logoUrl: SEED_AGENCIES.norte.logoUrl,
      phone: SEED_AGENCIES.norte.phone,
      email: SEED_AGENCIES.norte.email,
      address: SEED_AGENCIES.norte.address,
    },
  },
  {
    id: "bol-10",
    title: "Casa familiar barrio El Mirador",
    type: "house",
    price: 220000,
    currency: "USD",
    operation: "sale",
    beds: 3,
    baths: 2,
    areaM2: 185,
    address: "Los Álamos 45, Bolívar",
    neighborhood: "Barrio El Mirador",
    lat: -36.2356,
    lng: -61.1208,
    photoCount: 14,
    coverUrl: "/images/properties/house-5.jpg",
    photos: [
      "/images/properties/house-5.jpg",
    ],
    description:
      "Cálida casa de estilo rústico contemporáneo en el exclusivo barrio residencial El Mirador. Construcción de primera calidad con muros dobles, revestimiento en piedra natural y carpintería de madera maciza. Amplio living comedor con techos de madera a la vista, cocina comedor diario, 3 dormitorios (principal en suite) y parque trasero con césped bermuda y galería.",
    features: [
      "Detalles constructivos en piedra y madera maciza",
      "Doble garaje cerrado con portón automatizado",
      "Galería con asador tradicional",
      "Master suite con hidromasaje y vestidor",
      "Tranquilidad absoluta a minutos del centro",
    ],
    agency: {
      name: SEED_AGENCIES.centro.name,
      logoUrl: SEED_AGENCIES.centro.logoUrl,
      phone: SEED_AGENCIES.centro.phone,
      email: SEED_AGENCIES.centro.email,
      address: SEED_AGENCIES.centro.address,
    },
  },
]
