import type { Property } from "@/lib/properties/types"

/** ~10 avisos near Bolívar centro for filters + distance demos. */
export const SEED_PROPERTIES: Property[] = [
  {
    id: "bol-01",
    title: "Casa de dos plantas sobre Av. San Martín",
    type: "house",
    price: 185000,
    currency: "USD",
    operation: "sale",
    beds: 3,
    baths: 2,
    areaM2: 210,
    address: "Av. San Martín 845, Bolívar",
    lat: -36.2295,
    lng: -61.1138,
    photoCount: 12,
    coverUrl: "/placeholders/house-1.svg",
    agency: {
      name: "Norte Propiedades",
      logoUrl: "/placeholders/agency.svg",
      phone: "5492281421101",
    },
  },
  {
    id: "bol-02",
    title: "Depto luminoso a una cuadra de la plaza",
    type: "apartment",
    price: 280000,
    currency: "ARS",
    operation: "rent",
    beds: 2,
    baths: 1,
    areaM2: 68,
    address: "Belgrano 320, Bolívar",
    lat: -36.2312,
    lng: -61.1151,
    photoCount: 8,
    coverUrl: "/placeholders/apt-1.svg",
    agency: {
      name: "Centro Inmobiliaria",
      logoUrl: "/placeholders/agency.svg",
      phone: "5492281456789",
    },
  },
  {
    id: "bol-03",
    title: "Lote residencial barrio Las Acacias",
    type: "lot",
    price: 42000,
    currency: "USD",
    operation: "sale",
    beds: 0,
    baths: 0,
    areaM2: 600,
    address: "Calle 14 entre 9 y 11, Bolívar",
    lat: -36.2268,
    lng: -61.1089,
    photoCount: 4,
    coverUrl: "/placeholders/lot-1.svg",
    agency: {
      name: "Campo & Ciudad",
      logoUrl: "/placeholders/agency.svg",
      email: "campo@inmo.local",
    },
  },
  {
    id: "bol-04",
    title: "PH reciclado con patio",
    type: "house",
    price: 95000,
    currency: "USD",
    operation: "sale",
    beds: 2,
    baths: 1,
    areaM2: 95,
    address: "Rivadavia 1120, Bolívar",
    lat: -36.2331,
    lng: -61.1172,
    photoCount: 15,
    coverUrl: "/placeholders/house-2.svg",
    agency: {
      name: "Norte Propiedades",
      logoUrl: "/placeholders/agency.svg",
      phone: "5492281421101",
    },
  },
  {
    id: "bol-05",
    title: "Monoambiente amoblado centro",
    type: "apartment",
    price: 195000,
    currency: "ARS",
    operation: "rent",
    beds: 1,
    baths: 1,
    areaM2: 38,
    address: "Pinto 512, Bolívar",
    lat: -36.2301,
    lng: -61.1148,
    photoCount: 6,
    coverUrl: "/placeholders/apt-2.svg",
    agency: {
      name: "Bolívar Homes",
      logoUrl: "/placeholders/agency.svg",
      phone: "2281443322",
    },
  },
  {
    id: "bol-06",
    title: "Casa quinta a 5 min del centro",
    type: "house",
    price: 145000,
    currency: "USD",
    operation: "sale",
    beds: 4,
    baths: 2,
    areaM2: 280,
    address: "Ruta 226 Km 312, Bolívar",
    lat: -36.2385,
    lng: -61.102,
    photoCount: 18,
    coverUrl: "/placeholders/house-3.svg",
    agency: {
      name: "Campo & Ciudad",
      logoUrl: "/placeholders/agency.svg",
      phone: "5492281987654",
    },
  },
  {
    id: "bol-07",
    title: "Depto 3 ambientes con cochera",
    type: "apartment",
    price: 78000,
    currency: "USD",
    operation: "sale",
    beds: 3,
    baths: 2,
    areaM2: 92,
    address: "Alsina 780, Bolívar",
    lat: -36.2284,
    lng: -61.1165,
    photoCount: 10,
    coverUrl: "/placeholders/apt-3.svg",
    agency: {
      name: "Centro Inmobiliaria",
      logoUrl: "/placeholders/agency.svg",
      phone: "5492281456789",
    },
  },
  {
    id: "bol-08",
    title: "Local + vivienda en esquina comercial",
    type: "house",
    price: 450000,
    currency: "ARS",
    operation: "rent",
    beds: 2,
    baths: 1,
    areaM2: 140,
    address: "Av. Bolívar y Sarmiento",
    lat: -36.2318,
    lng: -61.1122,
    photoCount: 9,
    coverUrl: "/placeholders/house-4.svg",
    agency: {
      name: "Bolívar Homes",
      logoUrl: "/placeholders/agency.svg",
      phone: "5492281332211",
    },
  },
  {
    id: "bol-09",
    title: "Lote comercial sobre avenida",
    type: "lot",
    price: 68000,
    currency: "USD",
    operation: "sale",
    beds: 0,
    baths: 0,
    areaM2: 450,
    address: "Av. San Martín 1500, Bolívar",
    lat: -36.2249,
    lng: -61.111,
    photoCount: 3,
    coverUrl: "/placeholders/lot-2.svg",
    agency: {
      name: "Norte Propiedades",
      logoUrl: "/placeholders/agency.svg",
      phone: "5492281421101",
    },
  },
  {
    id: "bol-10",
    title: "Casa familiar barrio El Mirador",
    type: "house",
    price: 220000,
    currency: "USD",
    operation: "sale",
    beds: 3,
    baths: 2,
    areaM2: 185,
    address: "Los Álamos 45, Bolívar",
    lat: -36.2356,
    lng: -61.1208,
    photoCount: 14,
    coverUrl: "/placeholders/house-5.svg",
    agency: {
      name: "Centro Inmobiliaria",
      logoUrl: "/placeholders/agency.svg",
      email: "centro@inmo.local",
    },
  },
]
